language: node_js
node_js:
  - "0.10"

script: make test-coveralls

before_script:
  - gulp --version
  - date --rfc-2822

after_script:
  - npm run coveralls
  
branches:
  only:
    - master

notifications:
  email: false
